kind: pipeline
type: kubernetes
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username: 
        from_secret: docker_user
      password:
        from_secret: docker_password
      repo: dockerhub.p.lodz.pl/boipxe/boipxe
      registry: dockerhub.p.lodz.pl
      auto_tag: true

      #trigger:
      #  event:
      #    - tag

